-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 21:12:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(30) NOT NULL,
  `ContactPerson` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`outlet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`outlet` (
  `ID` INT GENERATED ALWAYS AS () VIRTUAL,
  `storey` INT UNSIGNED NOT NULL COMMENT 'этаж',
  `area` INT NOT NULL COMMENT 'Площадь',
  `PresenceOfAirConditioning` TINYINT UNSIGNED NOT NULL COMMENT 'Наличие кондиционера',
  `RentalCostPerDay` DECIMAL UNSIGNED NOT NULL COMMENT 'Стоимость аренды в день',
  `AllocatedPowerKilowatts` DOUBLE UNSIGNED NOT NULL COMMENT 'Число выделенных киловат',
  `NumberOfWindows` INT UNSIGNED NOT NULL COMMENT 'Число окон',
  `InventoryNumber` INT UNSIGNED NOT NULL COMMENT 'Инвертарный номер',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `InventoryNumber_UNIQUE` (`InventoryNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agreement` (
  `ID` INT NOT NULL,
  `outlet_id` INT NOT NULL COMMENT 'Торговая точка',
  `client_id` INT NOT NULL,
  `DateStart` DATE NOT NULL,
  `DateStop` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`outlet` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `D`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Clients` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomerDetails` (
  `ID` INT NOT NULL,
  `TYPE` LONGTEXT NOT NULL,
  `MeaningOfTheProps` LONGTEXT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Clients` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
